---
grails:
    profile: web
    codegen:
        defaultPackage: com.buffer
    spring:
        transactionManagement:
            proxies: false
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
spring:
    main:
        banner-mode: "off"
    groovy:
        template:
            check-template-location: false

# Spring Actuator Endpoints are Disabled by Default
endpoints:
    enabled: false
    jmx:
        enabled: true

---
grails:
    mime:
        disable:
            accept:
                header:
                    userAgents:
                        - Gecko
                        - WebKit
                        - Presto
                        - Trident
        types:
            all: '*/*'
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            form: application/x-www-form-urlencoded
            html:
              - text/html
              - application/xhtml+xml
            js: text/javascript
            json:
              - application/json
              - text/json
            multipartForm: multipart/form-data
            pdf: application/pdf
            rss: application/rss+xml
            text: text/plain
            hal:
              - application/hal+json
              - application/hal+xml
            xml:
              - text/xml
              - application/xml
    urlmapping:
        cache:
            maxsize: 1000
    controllers:
        defaultScope: singleton
    converters:
        encoding: UTF-8
    views:
        default:
            codec: html
        gsp:
            encoding: UTF-8
            htmlcodec: xml
            codecs:
                expression: html
                scriptlets: html
                taglib: none
                staticparts: none
    plugin:
        springsecurity:
            useSecurityEventListener:   true
endpoints:
    jmx:
        unique-names: true

---
hibernate:
    cache:
        queries: false
        use_second_level_cache: true
        use_query_cache: false
        region.factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory

dataSource:
    pooled: true
    jmxExport: true
#    driverClassName: org.h2.Driver
#    username: sa
#    password:
    driverClassName: com.mysql.jdbc.Driver
    dialect: org.hibernate.dialect.MySQL5InnoDBDialect

environments:
    development:
        server:
            session:
                timeout:    1800 # seconds
        dataSource:
            dbCreate: update
            pooled: true
#            url: jdbc:mysql://localhost:3306/tt_portal_utv
#            username: dbuser
#            password: dbuser
            url: jdbc:jtds:sqlserver://localhost:1433/tt_portal_utv
            driverClassName: net.sourceforge.jtds.jdbc.Driver
            dialect: org.hibernate.dialect.SQLServer2008Dialect
            username: sa
            password: woods2011
            properties :
                maxActive: 50
                maxIdle: 25
                minIdle: 1
                initialSize: 1

                numTestsPerEvictionRun: 3
                maxWait: 10000

                testOnBorrow: true
                testWhileIdle: true
                testOnReturn: true

                validationQuery: "select 1"

                minEvictableIdleTimeMillis: 300000
                timeBetweenEvictionRunsMillis: 300000

    test:
        dataSource:
            dbCreate: update
            url: jdbc:h2:mem:testDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    production:
        dataSource:
            dbCreate: none
            pooled: true
#            url: jdbc:jtds:sqlserver://localhost:1433/tt_portal_utv
            url: jdbc:jtds:sqlserver://192.168.225.11:1433/tt_sys
            driverClassName: net.sourceforge.jtds.jdbc.Driver
            dialect: org.hibernate.dialect.SQLServer2008Dialect
            username: sa
#            password: woods2011
            password: Avoc3nt
            properties :
                maxActive: 50
                maxIdle: 25
                minIdle: 1
                initialSize: 1

                numTestsPerEvictionRun: 3
                maxWait: 10000

                testOnBorrow: true
                testWhileIdle: true
                testOnReturn: true

                validationQuery: "select 1"

                minEvictableIdleTimeMillis: 300000
                timeBetweenEvictionRunsMillis: 300000
        server:
            port:  8443                                 # The port to listen on
            ssl:
                enabled: true                           # Activate HTTPS mode on the server port
            key-store: "D:/tomcat/keyStore/.keystore"         # e.g. /etc/tomcat7/keystore/tomcat.keystore
            key-store-password: jO9YxprVlix2cdL32W7w    # e.g. changeit
            key-alias: tomcat                           # e.g. tomcat
            key-password: jO9YxprVlix2cdL32W7w

